### ISSUE TITLE
Python Code On Android

### ISSUE THREAD

**Issue by utsav-shrma** [IOSD/gesture-based-mouse-control#2]
How do I run code written in python to run on android studio?
Please include it on resource also.

**Comment by menikhilpandey** [comment]
The primary way to do this is by creating an API. Here is the resource video which you can watch to understand what is an API if you're not familiar with it. https://www.youtube.com/watch?time_continue=7&v=s7wmiS2mSXY
You can make an API using Flask (Python Framework) and run all your python code in the API server and just make calls from your Android App. 
Here is a tutorial for the same.
https://android.jlelse.eu/handmade-backend-for-android-app-using-python-flask-framework-b173ba2bb3aa
Try it, in case of any difficulties you can comment further in this thread.
