### ISSUE TITLE
Error Running Hough Circle Detection

### ISSUE THREAD

**Issue by utsav-shrma** [IOSD/gesture-based-mouse-control#4]
//code As Follows

#######################################################
`

import cv2
import numpy as np
cap = cv2.VideoCapture(0)

while 1:
    
  ret ,img = cap.read()

 
  img = cv2.medianBlur(img,5)
  cimg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

  circles = cv2.HoughCircles(cimg,cv2.HOUGH_GRADIENT,1,20,
                            param1=50,param2=30,minRadius=0,maxRadius=100)

  circles = np.uint16(np.around(circles))
  for i in circles[0,:]:
      # draw the outer circle
      cv2.circle(img,(i[0],i[1]),i[2],(0,255,0),2)
      # draw the center of the circle
      cv2.circle(img,(i[0],i[1]),2,(0,0,255),3)
  cv2.imshow('detected circles',img)

  cv2.waitKey(0)
cv2.destroyAllWindows()
`
###################################################
works fine for images but keeps crashing with video feed as input.

**Comment by menikhilpandey** [comment]
waitkey expects key prompt, that is why your code is crashing, please try the following sample code :
import numpy as np
import cv2
cap = cv2.VideoCapture(0)
while cap.isOpened():
&nbsp;&nbsp;&nbsp;&nbsp;flags, frame = cap.read()
&nbsp;&nbsp;&nbsp;&nbsp;gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
&nbsp;&nbsp;&nbsp;&nbsp;cv2.imshow('img', gray)
&nbsp;&nbsp;&nbsp;&nbsp;key = cv2.waitKey(0) & 0xFF
&nbsp;&nbsp;&nbsp;&nbsp;if key == ord("q"):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break
cap.release()
cv2.destroyAllWindows()

**Comment by utsav-shrma** [comment]
Found the solution

`
cv2.imshow('img', gray)
    key = cv2.waitKey(30) & 0xFF
    if key == ord("q"):
        break
`
just changed this and the wait key parameter to 30 and worked just fine
as waitkey(0) shows 1 st frame infinitely until key is pressed as it waits for a keystroke to show the next Frame

Thanks
